### ISSUE TITLE
Errors when default Next Vehicle/Previous Vehicle bindings are not set

### ISSUE THREAD

**Issue by spocane** [sperrgebiet/FS19_VehicleExplorer#13]
get the following spammed if the default Next Vehicle/Previous Vehicle bindings are not set

`2019-03-04 19:01 Error: Running LUA method 'update'.`
`2019-03-04 19:01 G:/Farming Simulator Instances/FS19 Instances/TESTING/FS19_VehicleExplorer/VehicleSort.lua:1904: attempt to index a nil value`

**Comment by sperrgebiet** [comment]
Thanks for reporting it. Also realized it on another machine. Fixed in 0.9.3.3, which will be available later today.

**Comment by Soilaq** [comment]
This is still an issue. Had to stop using the mod sadly cause it wouldn't let me tab through all my vehicles. No matter how I rebound the keys etc.
